### ISSUE TITLE
[Control] Change Control types

### ISSUE THREAD

**Issue by Steven-Harris** [StevenHarrisDev/dashboard#16]
1. Gender should be a drop down
2. Shoots should be a drop down
3. chinese sign is not zodiac signs

**Comment by Steven-Harris** [comment]
@dheadt should #2 be a drop down? if so, what should the values be. Also, what should #3 be like. I am not following what it should be

**Comment by dheadt** [comment]
@Steven-Harris yes Shoots should be a drop down with Left, Right.  Its like what hand they shoot with.

**Comment by Steven-Harris** [comment]
@dheadt ohhhh, the makes sense now

**Comment by Steven-Harris** [comment]
@dheadt still need to know what you mean on #3

**Comment by dheadt** [comment]
Chinese sign is a different type of sign.  Like Monkey goat etc not the zodiac signs that we have.  I don't think she gave me those signs yet. I will ping her and ask. @Steven-Harris
